<?php

namespace AppBundle\Repository;

/**
 * MailAliasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MailAliasRepository extends \Doctrine\ORM\EntityRepository
{
}
