<?php

namespace AppBundle\Repository;

/**
 * MailUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MailUserRepository extends \Doctrine\ORM\EntityRepository
{
}
